### ISSUE TITLE
Notice: deleting official wiki page

### ISSUE THREAD

**Issue by arkon** [Efreak/tachiyomi-extensions#1]
We're working on moving all wiki info the website, so I'll be deleting [the wiki page](https://github.com/inorichi/tachiyomi/wiki/F-Droid-for-Dev-Versions).

For your record:

---

**Note that F-Droid is no longer an officially supported option** (see [#1625](https://github.com/inorichi/tachiyomi/pull/1625) and [#1907](https://github.com/inorichi/tachiyomi/pull/1907)).

**The dev versions now include an autoupdate mechanism**.

----------

There is an **unofficial** [F-Droid](https://f-droid.org/packages/org.fdroid.fdroid/) repo available, maintained by @Efreak, available at https://github.com/Efreak/tachiyomi-extensions  

Repo URL: `https://tachi.efreakbnc.net/fdroid/repo`  
Fingerprint (optional): `65F5EF1A9AE6FD7739FFB62E7C7021775198501780312BE1B782D4CA9FE07957`

### How-to
1. Install [F-Droid](https://f-droid.org/packages/org.fdroid.fdroid/) ([direct](https://f-droid.org/FDroid.apk))
2. Add `https://tachi.efreakbnc.net/fdroid/repo` as repo to F-Droid (Settings > Repositories > Plus)  
Or open [this link](https://tachi.efreakbnc.net/fdroid/repo?fingerprint=65F5EF1A9AE6FD7739FFB62E7C7021775198501780312BE1B782D4CA9FE07957) with F-Droid app.

#### Available apps
* `Tachiyomi (dev)` (app id `eu.kanade.tachiyomi.debug`) - Main app built from master branch
* `Tachiyomi (stable)` (app id `eu.kanade.tachiyomi`)
* All Tachiyomi extensions
* Other manga readers like `Neko`, `Meow`, etc.

<details>
<summary>Outdated information</summary>

There is an [F-Droid](https://f-droid.org/packages/org.fdroid.fdroid/) repo available, maintained by [@j2ghz](https://github.com/j2ghz), available at https://github.com/j2ghz/repo

Repo URL: `https://j2ghz.github.io/repo/`

### How-to
1. Install [F-Droid](https://f-droid.org/packages/org.fdroid.fdroid/) ([direct](https://f-droid.org/FDroid.apk))
2. Add `https://j2ghz.github.io/repo/` as repo to F-Droid (Three-dot menu > Repositories > Plus)

#### Available apps
* `Tachiyomi (dev)` (app id `eu.kanade.tachiyomi.debug`) - Main app built from master branch
</details>

**Comment by Efreak** [comment]
Thanks for letting me know.

I should like to note, regarding [#1907](https://github.com/inorichi/tachiyomi/pull/1907) or in case this information is posted somewhere, that the F-Droid repo (this one or any other) will *not* work for the official Tachiyomi extensions without first making uses-feature=tachiyomi.extension optional (I have a pull request ([#1434](https://github.com/inorichi/tachiyomi-extensions/pull/1434)) for this; alternatively using some other method to identify extensions), as fdroid will refuse to update.

You can deal with this by adding the feature to your devices (which is what I've done), but this requires root and manual editing of system XML files, and is hardly something I recommend.

You will still be able to update manually without this, but it would require having incompatible apps enabled, and you'll have to uninstall each extension before reinstalling as fdroid will only install and not update incompatible apps. (It would be nice if fdroid would check *why* an update is incompatible, and install regardless if said reason applied to the currently installed version as well)

Regarding the single-sources comment on the closed issue, I had actually considered that this is not the official source, but the reason I stated doing this us because I have Tachiyomi installed on three different android devices, with most scan group extensions and several others installed; updating them was an annoyance that disappeared entirely with this; if you've got an official repo, or other method of background installation, I'm happy to discontinue this in favor of that.
